[package]
name = "hestia"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
controllers = { workspace = true }
gpui-kit = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
