[package]
name = "hestia"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
controllers = { workspace = true }
gpui-kit = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
gpui-wry = "0.6.4"
wry = { package = "lb-wry", version = "0.53.3" }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["NSApplication", "NSBezierPath", "NSColor", "NSImage", "block2"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["NSData", "NSGeometry"] }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
